In [3]:
#3
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
#a
print("access 1st row,2column",arr[0,1])
#b
print("access 3rd row ,1stcolumn",arr[2,0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
access 1st row,2column 20
access 3rd row ,1stcolumn 70
