In [2]:
#5
import numpy as np
ucs420_manya = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("array:\n",ucs420_manya)

array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [3]:
mean=np.mean(ucs420_manya)
print("mean:",mean)

mean: 43.333333333333336


In [4]:
median=np.median(ucs420_manya)
print("median:",median)

median: 37.5


In [5]:
max=np.max(ucs420_manya)
print("max:",max)

max: 90


In [6]:
min=np.min(ucs420_manya)
print("min:",min)

min: 10


In [7]:
unique=np.unique(ucs420_manya)
print("unique:",unique)

unique: [10 15 20 30 35 40 50 60 70 80 90]


In [10]:
reshape_ucs420_manya=ucs420_manya.reshape(4,3)
print("reshape:\n",reshape_ucs420_manya)

reshape:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [11]:
resize_ucs420_manya=np.resize(ucs420_manya,(2,6))
print("resize_array:\n",resize_ucs420_manya)

resize_array:
 [[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
