In [1]:
import numpy as np
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(gfg)

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]


In [4]:
#1.1
total_sum=np.sum(gfg)
print(total_sum)
#1.2
row_sum=np.sum(gfg,axis=1)
print("row_sum\n",row_sum)
#1.3
column_sum=np.sum(gfg,axis=0)
print("\ncolumn_sum=",column_sum)

45
row_sum
 [[14]
 [16]
 [15]]

column_sum= [[20  9 16]]
