In [1]:
#2
import numpy as np
array= np.array([10,52,62,16,16,54,453])
#i
sorted_arr=np.sort(array)
print(sorted_arr)
#ii
sorted_indices= np.argsort(array)
print(sorted_indices)
#iii
smallest_4= np.sort(array)[:4]
print(smallest_4)
#iv
largest_5= np.sort(array)[-5:]
print(largest_5)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [2]:
#b
arr1=np.array([1.0,1.2,2.2,2.0,3.0,2.0])
#i
integer_element=arr1[arr1==arr1.astype(int)]
print(integer_element)
#ii
float_element=arr1[arr1!=arr1.astype(int)]
print(float_element)

[1. 2. 3. 2.]
[1.2 2.2]
